In [2]:
import numpy as np


In [10]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a.dtype

dtype('int64')

In [13]:
type(a)

numpy.ndarray

In [18]:
a = a.astype(np.float64)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
a[0][1]

2.0

In [23]:
import pandas as pd

fruits = pd.Series(['Apple', 'Banana', 'Orange', 'Grape', 'Mango'])

fruits


0     Apple
1    Banana
2    Orange
3     Grape
4     Mango
dtype: object

In [24]:
fruits.values

array(['Apple', 'Banana', 'Orange', 'Grape', 'Mango'], dtype=object)

In [25]:
fruits.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
prices = pd.Series([1000, 500, 800, 1200, 1500], 
                  index=['Apple', 'Banana', 'Orange', 'Grape', 'Mango'])
print("\n과일 가격 시리즈 (커스텀 인덱스):")
print(prices)


과일 가격 시리즈 (커스텀 인덱스):
Apple     1000
Banana     500
Orange     800
Grape     1200
Mango     1500
dtype: int64


In [28]:

# 인덱스로 데이터 선택하기
print("\n'Grape'의 가격:", prices['Grape'])  # 단일 값 선택
print("\n'Apple'과 'Mango'의 가격:")
print(prices[['Apple', 'Mango']])  # 여러 값 선택



'Grape'의 가격: 1200

'Apple'과 'Mango'의 가격:
Apple    1000
Mango    1500
dtype: int64


In [29]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

print(a+b)

[ 2  4  6  8 10]


In [30]:
print(a+5)

[ 6  7  8  9 10]


In [1]:
!git log


fatal: your current branch 'main' does not have any commits yet


In [4]:
!git remote add origin https://github.com/welovecherry/jupyter_prac.git

error: remote origin already exists.


In [ ]:
!git add .


In [ ]:
!ls -al

In [ ]:
!pwd

In [ ]:
import os
print(os.getcwd())  # 현재 작업 디렉토리 출력
print(os.listdir())  # 현재 디렉토리의 파일 목록 출력

In [ ]:
%%bash
ls -al
pwd